name: Docker Checks

on:
  workflow_dispatch:
  push:
    paths-ignore:
      - 'images/**'
      - '.github/workflows/**'
      - 'bin/server.rb'
      - 'events_listing/**'
      - '!.github/workflows/docker_checks.yml'

env:
  COMPOSE_DOCKER_CLI_BUILD: 1
  # It counts some attestation etc packages, each commit gives 3 pckages
  OLD_VERSIONS_TO_KEEP: 75 # 25 commits
  DOCKER_BUILD_CHECKS_ANNOTATIONS: false

permissions:
  contents: read
  packages: write

jobs:
  tests:
    runs-on: ubuntu-latest
    env:
      COMPOSE_FILE: docker-compose.ci.yml
    steps:
      - uses: actions/checkout@v4

      - uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: Dockerfile
          ignore: DL3006

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository }}
          tags: |
            # full length sha
            type=raw,enable=true,priority=300,prefix=,suffix=,value=dev

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        id: buildx_test
        uses: docker/setup-buildx-action@v3

      - name: Build
        uses: docker/build-push-action@v6
        with:
          push: true
          load: true
          cache-from: type=gha
          cache-to: type=gha,mode=max
          target: ci
          # Used by docker-compose.ci
          tags: ${{ steps.meta.outputs.tags }}

      - name: Run Rubocop
        run: |
          docker compose run --rm app rubocop

      - name: Run Tests
        run: |
          docker compose run --rm app rake test

      - name: Build Jekyll site
        run: |
          docker compose run --rm app jekyll build --source events_listing --destination _site

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Run be-a11y
        run: pnpm dlx @belenkadev/be-a11y _site
