name: Regenerate events.ics

on:
  push:
    paths:
      - 'bin/spreadsheet_to_ical'
  repository_dispatch:
    types: [regenerate-events]
  workflow_dispatch:

env:
  COMPOSE_DOCKER_CLI_BUILD: 1
  COMPOSE_FILE: docker-compose.ci.yml

jobs:
  regenerate:
    runs-on: ubuntu-latest

    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # added or changed files to the repository.
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: true  # ensure the action can push changes

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build
        uses: docker/build-push-action@v6
        with:
          push: false
          load: true
          cache-from: type=gha
          cache-to: type=gha,mode=max
          target: ci
          # Used by docker-compose.ci
          tags: image_ci:latest

      - name: Download CSV with events
        run: |
          curl -Lo events.csv "https://docs.google.com/spreadsheets/d/e/2PACX-1vTzDO4xR7fFMB53s98OETbwFNzhiMJ7N2I-kroaNQt4iB3mUthr7z1wGj3NhRXpVi8MQDzFKB0UjY9G/pub?gid=0&single=true&output=csv"

      - name: Generate events.ics
        run: docker compose run --rm app bin/spreadsheet_to_ical -o events.ics

      - name: Auto-commit updated events.ics
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Regenerate events files"
          file_pattern: "events.ics events.csv"
