name: Regenerate events.ics

on:
  push:
    paths:
      - 'bin/spreadsheet_to_ical'
      - 'images/inbox/**'
      - '.github/workflows/regenerate_events.yml'
    branches:
      - main
  repository_dispatch:
    types: [regenerate-events]
  workflow_dispatch:

jobs:
  convert:
    runs-on: ubuntu-latest

    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # added or changed files to the repository.
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: true

      - name: Install ImageMagick
        run: |
          sudo apt-get update
          sudo apt-get install -y imagemagick webp

      - name: Convert images to WebP
        run: |
          for img in images/inbox/*; do
            [ -f "$img" ] || continue
            if [ "$(basename "$img")" = ".gitkeep" ]; then continue; fi
            filename="$(basename "$img")"
            basename_no_ext="${filename%.*}"
            output="events_listing/assets/images/${basename_no_ext}.webp"
            convert "$img" -resize 900x900\> -quality 80 "$output"
            rm "$img"
          done

      - name: Auto-commit converted images
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Convert images to WebP"
          file_pattern: "events_listing/assets/images/*.webp images/inbox/*"

  regenerate:
    runs-on: ubuntu-latest
    needs: convert

    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # added or changed files to the repository.
      contents: write

    steps:
      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: true  # ensure the action can push changes

      - name: Download CSV with events
        run: |
          curl -Lo events.csv "https://docs.google.com/spreadsheets/d/e/2PACX-1vTzDO4xR7fFMB53s98OETbwFNzhiMJ7N2I-kroaNQt4iB3mUthr7z1wGj3NhRXpVi8MQDzFKB0UjY9G/pub?gid=0&single=true&output=csv"

      - name: Generate events.ics
        run: docker compose run app bin/spreadsheet_to_ical -o events.ics
        env:
          COMPOSE_FILE: docker-compose.ci.yml

      - name: Auto-commit updated events.ics
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Regenerate events files"
          file_pattern: "events.ics events.csv"
