name: Regenerate events.ics

on:
  repository_dispatch:
    types: [regenerate-events]
  workflow_dispatch:

jobs:
  regenerate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: true  # ensure the action can push changes

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build
        uses: docker/build-push-action@v6
        with:
          push: false
          load: true
          cache-from: type=gha
          cache-to: type=gha,mode=max
          target: ci
          # Used by docker-compose.ci
          tags: image_ci:latest

      - name: Generate events.ics
        run: docker compose run --rm app bin/spreadsheet_to_ical -o events.ics

      - name: Auto-commit updated events.ics
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Regenerate events.ics"
          file_pattern: "events.ics"
