name: Regenerate events.ics

on:
  push:
    paths:
      - 'bin/spreadsheet_to_ical'
      - '.github/workflows/regenerate_events.yml'
    branches:
      - main
  repository_dispatch:
    types: [regenerate-events]
  workflow_dispatch:

jobs:
  regenerate:
    runs-on: ubuntu-latest

    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # added or changed files to the repository.
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: true  # ensure the action can push changes

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Download CSV with events
        run: |
          curl -Lo events.csv "https://docs.google.com/spreadsheets/d/e/2PACX-1vTzDO4xR7fFMB53s98OETbwFNzhiMJ7N2I-kroaNQt4iB3mUthr7z1wGj3NhRXpVi8MQDzFKB0UjY9G/pub?gid=0&single=true&output=csv"

      - name: Generate events.ics
        run: docker compose run app bin/spreadsheet_to_ical -o events.ics
        env:
          COMPOSE_FILE: docker-compose.ci.yml

      - name: Auto-commit updated events.ics
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Regenerate events files"
          file_pattern: "events.ics events.csv"
          push_options: --force # Add force push
